<a href="https://colab.research.google.com/github/NatashaKamami/Python-Data-Analysis/blob/main/Numpy5_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Exercise 5

### All of the questions in this exercise are attributed to rougier/numpy-100

In [ ]:
import numpy as np

#### 61. Find the nearest value from a given value in an array (★★☆)

In [ ]:
array = np.array([1, 2, 3, 4, 5])
value = 3.6
nearest_value = array[(np.abs(array - value)).argmin()]
print(nearest_value)

4


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [ ]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y

print(A)
print(B)
print(it.operands[2])

[[0]
 [1]
 [2]]
[[0 1 2]]
[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [ ]:
class NameArray(np.ndarray):
    def __new__(cls, array, name):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj

Z = NameArray(np.arange(10), "range_10")
print (Z.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [ ]:
vector = np.array([10, 20, 30, 40])
indices = np.array([0, 2, 2])  # Adding 1 to indices 0 and 2 (which are repeated)
vector[indices] += 1

print(vector)

[11 20 31 40]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [ ]:
X = np.array([0, 0, 0])
values = np.array([1, 2, 3, 4])
indices = np.array([0, 1, 0, 1])  # Accumulating at indices 0 and 1
np.add.at(X, indices, values)


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [ ]:
# Example image of shape (height, width, 3)
image = np.random.randint(0, 256, (100, 100, 3), dtype=np.ubyte)

# Reshape the image to a 2D array of shape (num_pixels, 3)
pixels = image.reshape(-1, 3)

# Find unique colors
unique_colors = np.unique(pixels, axis=0)
num_unique_colors = unique_colors.shape[0]
print(num_unique_colors)


9996


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [ ]:
array = np.random.rand(4, 3, 2, 5)  # Example 4D array
sum_result = np.sum(array, axis=(-1, -2))  # Sums over the last two axes
print(sum_result)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [ ]:
D = np.array([10, 20, 30, 40, 50])
S = np.array([0, 1, 0, 1, 0])  # Subset indices

means = np.zeros(S.max() + 1)
counts = np.zeros(S.max() + 1)

np.add.at(means, S, D)
np.add.at(counts, S, 1)

mean_values = means / counts  # Avoid division by zero if necessary
print(mean_values)

[30. 30.]


#### 69. How to get the diagonal of a dot product? (★★★)

In [ ]:
A = np.random.rand(3, 4)
B = np.random.rand(4, 3)

# Compute the dot product
dot_product = np.dot(A, B)

# Get the diagonal
diagonal = np.diagonal(dot_product)

print(diagonal)

[0.39160834 0.86215815 0.8443731 ]


#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [ ]:
vector = np.array([1, 2, 3, 4, 5])
new_vector = np.zeros(len(vector) + 3 * (len(vector) - 1), dtype=vector.dtype)

new_vector[::4] = vector  # Place original values in every fourth position
print(new_vector)

[1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [ ]:
array_3d = np.random.rand(5, 5, 3)  # Shape (5, 5, 3)
array_2d = np.random.rand(5, 5)      # Shape (5, 5)

# Broadcasting multiplication
result = array_3d * array_2d[:, :, np.newaxis]  # Shape (5, 5, 3)
print(result)

[[[1.47428436e-01 1.24821913e-01 2.01677615e-01]
  [1.46350944e-01 5.92225397e-02 1.36287043e-01]
  [1.47344882e-01 2.96666919e-01 2.35685640e-02]
  [7.83247238e-01 8.80021314e-02 2.21931468e-01]
  [3.78695557e-01 1.41065055e-02 5.80795334e-01]]

 [[1.46536572e-01 4.83314582e-02 3.16752196e-01]
  [3.61378167e-01 7.90958953e-02 3.81728749e-01]
  [6.96046797e-01 1.36067639e-01 8.23819884e-01]
  [6.55652884e-01 7.87953774e-01 7.60835175e-01]
  [3.35011725e-01 3.41149399e-01 2.23656739e-01]]

 [[5.90853814e-02 4.55452773e-03 4.92742181e-02]
  [6.63762806e-02 8.61872879e-02 5.72185925e-02]
  [4.68854220e-01 9.02464476e-01 8.62988115e-01]
  [2.84939272e-02 8.90953195e-02 6.74803622e-02]
  [1.41313300e-01 1.74538252e-01 1.09596675e-01]]

 [[5.99248341e-02 5.59304003e-02 1.71648695e-01]
  [2.21033002e-01 3.13743788e-01 6.23968216e-02]
  [5.99748206e-02 4.23412567e-03 3.33096733e-01]
  [2.32810917e-02 4.52225372e-01 4.37968363e-01]
  [2.55712833e-02 1.31546571e-02 2.75616632e-02]]

 [[1.4683591

#### 72. How to swap two rows of an array? (★★★)

In [ ]:
array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Swap row 0 and row 1
array[[0, 1]] = array[[1, 0]]

print(array)

[[4 5 6]
 [1 2 3]
 [7 8 9]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [ ]:
triangles = np.array([[0, 1, 2], [1, 2, 3], [0, 2, 3], [0, 1, 3]])

segments = set()
for triangle in triangles:
    segments.update({tuple(sorted([triangle[i], triangle[j]])) for i in range(3) for j in range(i + 1, 3)})

unique_segments = np.array(list(segments))

print(unique_segments)

[[0 1]
 [1 2]
 [0 3]
 [2 3]
 [0 2]
 [1 3]]


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [ ]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [ ]:
def sliding_window_average(arr, window_size):
    kernel = np.ones(window_size) / window_size
    return np.convolve(arr, kernel, mode='valid')

array = np.array([1, 2, 3, 4, 5, 6])
averages = sliding_window_average(array, window_size=3)
print(averages)

[2. 3. 4. 5.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [ ]:
Z = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])
n_rows = len(Z) - 3 + 1

# Build the 2D array
shifted_array = np.array([Z[i:i+3] for i in range(n_rows)])
print(shifted_array)

[[ 1  2  3]
 [ 2  3  4]
 [ 3  4  5]
 [ 4  5  6]
 [ 5  6  7]
 [ 6  7  8]
 [ 7  8  9]
 [ 8  9 10]
 [ 9 10 11]
 [10 11 12]
 [11 12 13]
 [12 13 14]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [ ]:
# Negate a boolean array
bool_array = np.array([True, False, True])
bool_array = ~bool_array  # In-place negation

# Change the sign of a float array
float_array = np.array([1.0, -2.0, 3.0])
float_array *= -1  # In-place sign change

print(float_array)

[-1.  2. -3.]


#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [ ]:
def point_to_line_distance(P0, P1, p):
    line_vec = P1 - P0
    point_vec = p - P0
    line_len_sq = np.sum(line_vec ** 2, axis=1)
    t = np.clip(np.einsum('ij,ij->i', point_vec, line_vec) / line_len_sq, 0, 1)
    closest_points = P0 + t[:, np.newaxis] * line_vec
    return np.linalg.norm(closest_points - p, axis=1)

P0 = np.array([[1, 2], [3, 4], [5, 6]])
P1 = np.array([[2, 3], [4, 5], [6, 7]])
p = np.array([2, 2])
distances = point_to_line_distance(P0, P1, p)

print(distances)

[0.70710678 2.23606798 5.        ]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [ ]:
def points_to_lines_distance(P0, P1, P):
    distances = np.zeros((P.shape[0], P0.shape[0]))
    for i, point in enumerate(P):
        distances[i, :] = point_to_line_distance(P0, P1, point)
    return distances

P = np.array([[1, 1], [2, 2], [3, 3]])
distances_to_lines = points_to_lines_distance(P0, P1, P)
print(distances_to_lines)

[[1.         3.60555128 6.40312424]
 [0.70710678 2.23606798 5.        ]
 [1.         1.         3.60555128]]


#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [ ]:
def extract_subpart(array, center, shape, fill_value=0):
    pad_width = [(s // 2, s // 2) for s in shape]
    padded_array = np.pad(array, pad_width, mode='constant', constant_values=fill_value)

    start = tuple(center[i] + pad_width[i][0] for i in range(len(center)))
    return padded_array[start[0]:start[0] + shape[0], start[1]:start[1] + shape[1]]

array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
subpart = extract_subpart(array, (1, 1), (2, 2))
print(subpart)

[[5 6]
 [8 9]]


#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [ ]:
Z = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])
window_size = 4

# Generate the sliding windows
R = np.array([Z[i:i + window_size] for i in range(len(Z) - window_size + 1)])
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [ ]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
rank = np.linalg.matrix_rank(A)
print(rank)

2


#### 83. How to find the most frequent value in an array?

In [ ]:
arr = np.array([1, 2, 2, 3, 4, 4, 4, 5])
unique, counts = np.unique(arr, return_counts=True)
most_frequent = unique[np.argmax(counts)]
print(most_frequent)

4


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [ ]:
matrix = np.random.rand(10, 10)
blocks = np.array([matrix[i:i + 3, j:j + 3] for i in range(8) for j in range(8)])  # 8x8 starting points
print(blocks)

[[[0.33314853 0.72801197 0.24353008]
  [0.18284577 0.64752208 0.7629114 ]
  [0.71726875 0.05024945 0.49131188]]

 [[0.72801197 0.24353008 0.83884746]
  [0.64752208 0.7629114  0.97972325]
  [0.05024945 0.49131188 0.87591448]]

 [[0.24353008 0.83884746 0.98496098]
  [0.7629114  0.97972325 0.88961501]
  [0.49131188 0.87591448 0.13219505]]

 [[0.83884746 0.98496098 0.00307237]
  [0.97972325 0.88961501 0.75245652]
  [0.87591448 0.13219505 0.04491642]]

 [[0.98496098 0.00307237 0.76661775]
  [0.88961501 0.75245652 0.76404782]
  [0.13219505 0.04491642 0.53292503]]

 [[0.00307237 0.76661775 0.90982598]
  [0.75245652 0.76404782 0.20155737]
  [0.04491642 0.53292503 0.27299792]]

 [[0.76661775 0.90982598 0.05751494]
  [0.76404782 0.20155737 0.85128952]
  [0.53292503 0.27299792 0.52442932]]

 [[0.90982598 0.05751494 0.50885384]
  [0.20155737 0.85128952 0.97913777]
  [0.27299792 0.52442932 0.58758709]]

 [[0.18284577 0.64752208 0.7629114 ]
  [0.71726875 0.05024945 0.49131188]
  [0.88524348 0.729833

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [ ]:
class SymmetricArray(np.ndarray):
    def __new__(cls, input_array):
        obj = np.asarray(input_array).view(cls)
        return obj

    def __getitem__(self, index):
        if isinstance(index, tuple):
            return super().__getitem__((index[1], index[0]))  # Swap indices for symmetry
        return super().__getitem__(index)

# Example usage
Z = SymmetricArray(np.array([[1, 2], [2, 1]]))
print(Z)

[[1 2]
 [2 1]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [ ]:
p = 5  # Number of matrices and vectors
n = 3  # Size of matrices
A = np.random.rand(p, n, n)  # p matrices of shape (n,n)
B = np.random.rand(p, n, 1)   # p vectors of shape (n,1)

# Compute the sum of the products
result = np.sum(A @ B, axis=0)  # Resulting shape will be (n,1)
print(result)

[[3.8444631 ]
 [3.24335457]
 [3.37830945]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [ ]:
array = np.random.rand(16, 16)
block_size = 4
block_sum = array.reshape(4, 4, block_size, block_size).sum(axis=(2, 3))
print(block_sum)

[[7.52665809 8.8386758  6.82807686 9.87674149]
 [6.55641415 8.28215196 8.90562607 7.20942378]
 [7.01727782 8.67791852 8.72461335 6.22403924]
 [8.17419409 9.04133478 8.46641389 5.95527987]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [ ]:
def game_of_life(board):
    neighbors = sum(np.roll(np.roll(board, i, 0), j, 1)
                    for i in (-1, 0, 1) for j in (-1, 0, 1))
    return (neighbors == 3) | (board & (neighbors == 2))

# Example usage
board = np.random.randint(0, 2, (10, 10))
next_board = game_of_life(board)
print(next_board)

[[1 0 1 0 0 0 1 1 1 0]
 [0 0 1 0 1 0 1 1 0 0]
 [0 0 0 0 0 1 1 0 0 0]
 [0 0 0 0 0 1 1 0 0 0]
 [0 0 1 0 0 1 1 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


#### 89. How to get the n largest values of an array (★★★)

In [ ]:
arr = np.array([1, 3, 5, 7, 9, 2, 4, 6, 8, 0])
n = 3
largest_values = np.partition(arr, -n)[-n:]  # Get the n largest values
print(largest_values)

[7 8 9]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [ ]:
vectors = [np.array([1, 2]), np.array([3, 4])]
product = np.array(np.meshgrid(*vectors)).T.reshape(-1, len(vectors))
print(product)

[[1 3]
 [1 4]
 [2 3]
 [2 4]]


#### 91. How to create a record array from a regular array? (★★★)

In [ ]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [ ]:
Z = np.array([1, 2, 3, 4, 5])

# Method 1: Using the `**` operator
method1 = Z ** 3

# Method 2: Using `np.power`
method2 = np.power(Z, 3)

# Method 3: Using `np.array` and `np.multiply`
method3 = np.array([np.multiply(Z[i], Z[i]) for i in range(len(Z))])
method3 = np.multiply(method3, Z)

print(method3)

[  1   8  27  64 125]


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [ ]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[0 1 6 7]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [ ]:
matrix = np.random.randint(1, 5, (10, 3))
unequal_rows = matrix[~np.all(matrix[:, None] == matrix[:, None, :], axis=2).any(axis=1)]
print(unequal_rows)

[]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [ ]:
vector = np.array([1, 2, 3])
binary_representation = np.unpackbits(vector[:, np.newaxis].astype(np.uint8), axis=1)
print(binary_representation)

[[0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [ ]:
array = np.random.randint(0, 5, (10, 3))
unique_rows = np.unique(array, axis=0)
print(unique_rows)

[[0 0 0]
 [0 1 1]
 [1 2 0]
 [1 3 3]
 [2 0 1]
 [2 0 4]
 [3 1 4]
 [4 1 3]
 [4 2 4]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [ ]:
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

# Inner product
inner_product = np.einsum('i,i->', A, B)
print(inner_product)

# Outer product
outer_product = np.einsum('i,j->ij', A, B)
print(outer_product)

# Sum
total_sum = np.einsum('i->', A)
print(total_sum)

# Element-wise multiplication
elementwise_mul = np.einsum('i,j->ij', A, B)
print(elementwise_mul)


32
[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]
6
[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [ ]:
import numpy as np

X = np.array([0, 1, 2, 3])
Y = np.array([0, 1, 0, -1])

# Sample equidistant points
t = np.linspace(0, 1, num=5)
sampled_points = np.vstack((np.interp(t, np.linspace(0, 1, len(X)), X),
                             np.interp(t, np.linspace(0, 1, len(Y)), Y))).T
print(sampled_points)

[[ 0.    0.  ]
 [ 0.75  0.75]
 [ 1.5   0.5 ]
 [ 2.25 -0.25]
 [ 3.   -1.  ]]


#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [ ]:
import numpy as np

n = 5
X = np.random.randint(0, n + 1, (10, 4))  # Example rows

valid_rows = X[np.sum(X, axis=1) == n]
print(valid_rows)

[]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [ ]:
X = np.random.rand(100)  # Example data
N = 1000  # Number of bootstrap samples
boot_means = np.random.choice(X, (N, len(X)), replace=True).mean(axis=1)
ci_lower, ci_upper = np.percentile(boot_means, [2.5, 97.5])
print(ci_lower, ci_upper)

0.40854356489861854 0.5157987694712594
