<a href="https://colab.research.google.com/github/NatashaKamami/Python-Data-Analysis/blob/main/Numpy3_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Exercise 3

### All of the questions in this exercise are attributed to rougier/numpy-100

In [ ]:
import numpy as np

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [ ]:
import warnings

# Suppress all warnings
warnings.filterwarnings("ignore")

# Example of code that might generate warnings
# For instance, performing an invalid operation
arr = np.array([1, 2, 3])
invalid_operation = arr / 0  # This would normally generate a warning

print(invalid_operation)


[inf inf inf]


#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
np.sqrt(-1) == np.emath.sqrt(-1)

<ipython-input-2-16339fbc685e>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [ ]:
today = np.datetime64('today', 'D')

yesterday = today - np.timedelta64(1, 'D')
tomorrow = today + np.timedelta64(1, 'D')

print("Yesterday's date:", yesterday)
print("Today's date:", today)
print("Tomorrow's date:", tomorrow)


Yesterday's date: 2024-10-26
Today's date: 2024-10-27
Tomorrow's date: 2024-10-28


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [ ]:
start_date = np.datetime64('2016-07-01')
end_date = np.datetime64('2016-08-01')  # Next day after July

# Generate all dates in July 2016
july_dates = np.arange(start_date, end_date, dtype='datetime64[D]')

print("All dates in July 2016:")
print(july_dates)


All dates in July 2016:
['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [ ]:
A = np.array([1, 2, 3], dtype=float)
B = np.array([4, 5, 6], dtype=float)

# Compute (A + B) in place in a temporary variable
temp = A + B

# Update A in place to compute the final result
A *= -0.5  # This updates A to -A/2
A *= temp  # This computes (A + B) * (-A/2) in place

print("Result in A:")
print(A)


Result in A:
[ -2.5  -7.  -13.5]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [ ]:
arr = np.random.rand(5) * 10  # Scale to get numbers between 0 and 10

# Method 1: Using np.floor
int_part_floor = np.floor(arr).astype(int)

# Method 2: Using np.trunc
int_part_trunc = np.trunc(arr).astype(int)

# Method 3: Using np.floor_divide
int_part_floor_divide = np.floor_divide(arr, 1)

# Method 4: Using type casting (astype)
int_part_cast = arr.astype(int)

# Print the original array and integer parts
print("Original Array:")
print(arr)
print("\nInteger Part using np.floor:")
print(int_part_floor)
print("\nInteger Part using np.trunc:")
print(int_part_trunc)
print("\nInteger Part using np.floor_divide:")
print(int_part_floor_divide)
print("\nInteger Part using astype(int):")
print(int_part_cast)


Original Array:
[9.20766604 7.49378048 1.03092231 0.21093763 6.65542251]

Integer Part using np.floor:
[9 7 1 0 6]

Integer Part using np.trunc:
[9 7 1 0 6]

Integer Part using np.floor_divide:
[9. 7. 1. 0. 6.]

Integer Part using astype(int):
[9 7 1 0 6]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [ ]:
matrix = np.tile(np.arange(5), (5, 1))

print("5x5 Matrix:")
print(matrix)


5x5 Matrix:
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [ ]:
import numpy as np

# Define the generator function
def generate_integers(n):
    for _ in range(n):
        yield np.random.randint(0, 100)  # Generate integers between 0 and 99

# Use the generator to build an array
generator = generate_integers(10)
array = np.array(list(generator))

print("Generated Array:")
print(array)


Generated Array:
[99 52  7 93 66 22 19  1 46 28]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [ ]:
import numpy as np

# Create a vector with values ranging from 0 to 1, both excluded
vector_linspace = np.linspace(0, 1, 12)[1:-1]  # Generates 12 points and excludes the first and last

print("Vector using np.linspace:")
print(vector_linspace)


Vector using np.linspace:
[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [ ]:
random_vector = np.random.rand(10)
sorted_vector = np.sort(random_vector)

print(random_vector)
print(sorted_vector)


[0.48313991 0.21956455 0.55441359 0.15559095 0.08252572 0.89700314
 0.45495979 0.71628588 0.21995712 0.84337122]
[0.08252572 0.15559095 0.21956455 0.21995712 0.45495979 0.48313991
 0.55441359 0.71628588 0.84337122 0.89700314]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [ ]:
small_array = [1, 2, 3, 4, 5]
result = sum(small_array)
print(result)

15


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [ ]:
A = np.random.rand(5)  # Array of size 5 with random values
B = np.random.rand(5)  # Another array of the same size with random values

# Check if they are equal
are_equal = np.array_equal(A, B)


print(A)
print(B)
print("\nAre A and B equal?", are_equal)


[0.17284307 0.4720461  0.71602738 0.36354219 0.41144299]
[0.2406358  0.75136411 0.09594569 0.82625949 0.75958125]

Are A and B equal? False


#### 43. Make an array immutable (read-only) (★★☆)

In [ ]:
arr = np.array([1, 2, 3, 4, 5])

# Make the array read-only
arr.setflags(write=False)

# Try to modify the array (this will raise an error)
try:
    arr[0] = 10
except ValueError as e:
    print(f"Error: {e}")

# You can still read the values
print(arr)


Error: assignment destination is read-only
[1 2 3 4 5]


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [ ]:
# Generate a random 10x2 matrix representing Cartesian coordinates
cartesian_coords = np.random.rand(10, 2)

# Extract x and y coordinates
x = cartesian_coords[:, 0]
y = cartesian_coords[:, 1]

# Convert to polar coordinates
r = np.sqrt(x**2 + y**2)               # radius
theta = np.arctan2(y, x)                # angle in radians

# Combine r and theta into a single array
polar_coords = np.column_stack((r, theta))

# Output the results
print("Cartesian coordinates:\n", cartesian_coords)
print("\nPolar coordinates (r, theta):\n", polar_coords)


Cartesian coordinates:
 [[0.16444063 0.15007776]
 [0.74679576 0.8810789 ]
 [0.99184014 0.52423595]
 [0.78007286 0.66514192]
 [0.41182483 0.50070521]
 [0.54411424 0.44897162]
 [0.56441546 0.42774989]
 [0.47619981 0.56282716]
 [0.15854509 0.47891424]
 [0.08046697 0.21563079]]

Polar coordinates (r, theta):
 [[0.22262986 0.73976366]
 [1.15499088 0.86770167]
 [1.12186015 0.48622498]
 [1.02514752 0.70604002]
 [0.64830965 0.88249185]
 [0.70543308 0.68988465]
 [0.70819121 0.6485148 ]
 [0.7372521  0.86857932]
 [0.50447537 1.25110118]
 [0.23015554 1.21363088]]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [ ]:
vector = np.random.rand(10)

max_index = np.argmax(vector)

vector[max_index] = 0

print("Random Vector:")
print(vector)


Random Vector:
[0.23394314 0.19422801 0.         0.57556867 0.12844642 0.8178774
 0.51612984 0.33937017 0.60791628 0.12734012]
