<a href="https://colab.research.google.com/github/NatashaKamami/Python-Data-Analysis/blob/main/Numpy2_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Exercise 2

### All of the questions in this exercise are attributed to rougier/numpy-100

In [ ]:
import numpy as np

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [ ]:
array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
bordered_array = np.pad(array, pad_width=1, mode='constant', constant_values=0)
print(bordered_array)


[[0 0 0 0 0]
 [0 1 2 3 0]
 [0 4 5 6 0]
 [0 7 8 9 0]
 [0 0 0 0 0]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [ ]:
matrix = np.zeros((5, 5))

for i in range(1, 5):
    matrix[i, i - 1] = i

print(matrix)


[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [ ]:
checkerboard = np.zeros((8, 8), dtype=int)

checkerboard[1::2, ::2] = 1  # Fill odd rows, even columns with 1
checkerboard[::2, 1::2] = 1  # Fill even rows, odd columns with 1

print(checkerboard)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [ ]:
# Define the shape of the array
shape = (6, 7, 8)

# The 100th element corresponds to index 99 (0-based index)
flat_index = 99

# Use np.unravel_index to convert flat index to multi-dimensional index
multi_index = np.unravel_index(flat_index, shape)

print(multi_index)  # Output will be (x, y, z)


(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [ ]:
checkerboard_pattern = np.array([[0, 1],
                                  [1, 0]])

checkerboard = np.tile(checkerboard_pattern, (4, 4))

print(checkerboard)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [ ]:
matrix = np.random.rand(5, 5)

#min max normalization
normalized_matrix = (matrix - matrix.min()) / (matrix.max() - matrix.min())

# Z-score normalization
mean = matrix.mean()
std = matrix.std()
z_normalized_matrix = (matrix - mean) / std

print(z_normalized_matrix)
print(matrix)
print(normalized_matrix)


[[0.59832056 0.69220643 0.31856187 0.9223425  0.12497117]
 [0.64614279 0.56910066 0.01562924 0.22273043 0.7212486 ]
 [0.80492225 0.35089672 0.24785033 0.9051356  0.18783858]
 [0.47941229 0.94605784 0.37841348 0.39343873 0.42534634]
 [0.69209085 0.90340704 0.4817561  0.24328805 0.37170232]]
[[0.62626119 0.72716724 0.32558396 0.97451139 0.11751781]
 [0.67765926 0.59485641 0.         0.22258687 0.75838099]
 [0.84831121 0.36033661 0.24958508 0.95601787 0.18508603]
 [0.49846173 1.         0.38991089 0.40605963 0.44035309]
 [0.72704301 0.95416005 0.50098079 0.24468165 0.38269791]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [ ]:
# Define the custom dtype for RGBA color
rgba_dtype = np.dtype([('r', np.uint8),
                       ('g', np.uint8),
                       ('b', np.uint8),
                       ('a', np.uint8)])

# Example: Create an array of RGBA colors using the custom dtype
colors = np.array([(255, 0, 0, 255),   # Red
                   (0, 255, 0, 255),   # Green
                   (0, 0, 255, 255),   # Blue
                   (255, 255, 0, 255)], # Yellow
                  dtype=rgba_dtype)

# Output the colors
print(colors)


[(255,   0,   0, 255) (  0, 255,   0, 255) (  0,   0, 255, 255)
 (255, 255,   0, 255)]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [ ]:
A = np.random.rand(5, 3)
B = np.random.rand(3, 2)
C = np.dot(A, B)

print(A)
print(B)
print(C)


[[0.25027805 0.58150232 0.8545501 ]
 [0.41887359 0.59205749 0.20220584]
 [0.43000077 0.37817894 0.91753155]
 [0.6633323  0.86170665 0.43066643]
 [0.10728128 0.44916097 0.49760862]]
[[0.40829558 0.98696926]
 [0.77427093 0.19169317]
 [0.94528339 0.95993344]]
[[1.36021978 1.17879799]
 [0.82057897 0.72101288]
 [1.33570771 1.37766107]
 [1.34513189 1.23328298]
 [0.86195592 0.66965558]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
arr[(arr >= 3) & (arr <= 8)] *= -1

print(arr)


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
z = np.random.randint(3,10, size=5)
z

array([4, 4, 8, 6, 7])

#### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

<ipython-input-11-cd809174da5d>:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
<ipython-input-11-cd809174da5d>:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)
<ipython-input-11-cd809174da5d>:3: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆)

In [ ]:
arr = np.array([-1.5, -2.3, 0.0, 1.2, 2.7])

rounded_arr = np.where(arr > 0, np.ceil(arr), np.floor(arr))

print(arr)
print(rounded_arr)


[-1.5 -2.3  0.   1.2  2.7]
[-2. -3.  0.  2.  3.]


#### 30. How to find common values between two arrays? (★☆☆)

In [ ]:
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([4, 5, 6, 7, 8])

common_values = np.intersect1d(array1, array2)
print(common_values)


[4 5]
