<a href="https://colab.research.google.com/github/NatashaKamami/Python-Data-Analysis/blob/main/Numpy_Exercise1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Exercise 1

### All of the questions in this exercise are attributed to rougier/numpy-100

#### 1. Import the numpy package under the name `np` (★☆☆)

In [ ]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [ ]:
np.__version__

'1.26.4'

#### 3. Create a null vector of size 10 (★☆☆)

In [ ]:
null_vector = np.zeros(10)
null_vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [ ]:
null_vector.nbytes

80

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [ ]:
np.add?

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [ ]:
null_vector1 = np.zeros(10)
null_vector1[4] = 1
null_vector1

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [ ]:
vector = np.arange(10, 49)
vector

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [ ]:
array = np.array([1, 3, 5, 7, 9])
array[::-1]

array([9, 7, 5, 3, 1])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [ ]:
vector1 = np.arange(0, 9).reshape(3,3)
vector1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [ ]:
array1 = np.array([1, 2, 0, 0, 4, 0])
np.nonzero(array1)

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [ ]:
identity_matrix = np.eye(3)
identity_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [ ]:
array3 = np.random.randint(1,10, size=(3,3,3))
array3

array([[[8, 8, 3],
        [1, 3, 6],
        [9, 7, 3]],

       [[7, 8, 6],
        [3, 5, 5],
        [5, 7, 4]],

       [[7, 5, 8],
        [8, 7, 6],
        [7, 5, 8]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [ ]:
array4 = np.random.rand(10,10)
min = np.min(array4)
max = np.max(array4)
#print(array4)
print(min)
print(max)

[[7.31182782e-01 9.89673755e-01 9.34428248e-01 5.02877510e-01
  9.66951619e-02 4.39628569e-01 5.76351756e-01 6.14491545e-01
  7.39027415e-01 9.32514782e-01]
 [2.06872512e-02 9.58224264e-01 5.25255193e-01 7.32746011e-04
  1.49568217e-01 4.44875720e-01 5.32973464e-01 8.56216431e-01
  2.57824750e-02 3.89395130e-01]
 [8.36688565e-01 9.23619120e-03 6.12922966e-01 6.41821268e-01
  4.66408083e-01 3.20623778e-01 6.38897125e-01 6.10012909e-01
  5.44290917e-01 9.94892392e-01]
 [3.68086659e-01 1.35788728e-01 5.92649268e-02 9.10197941e-01
  4.92826619e-01 9.71933494e-01 8.76198426e-01 2.32193720e-01
  8.04765206e-01 1.81944165e-02]
 [8.05814153e-01 2.64624090e-01 3.70030307e-01 8.19095132e-03
  1.41643870e-01 2.57747243e-02 5.79453190e-02 8.04716151e-01
  8.55037101e-01 8.09963334e-01]
 [1.73288525e-01 8.97251983e-01 4.80000265e-01 4.03836612e-01
  6.51649175e-01 2.36293289e-01 4.82715169e-01 4.56749891e-01
  2.22385308e-01 7.74609672e-01]
 [4.70374120e-03 8.30304630e-01 6.46700314e-01 9.41328823e

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [ ]:
random_vector = np.random.randint(1, 100, size=(30))
mean = np.mean(random_vector)
print(random_vector)
print(mean)

[33 79 24 66 43 21 87 60 53 73 27 26 73 64 19 88 92 87 56 20 75 82  6 52
 61 82 64 71 39 80]
56.766666666666666


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [ ]:
import numpy as np

def create_border_array(rows, cols):
    # Create an array filled with zeros
    array = np.zeros((rows, cols), dtype=int)

    # Set the border elements to 1
    array[0, :] = 1        # Top border
    array[-1, :] = 1       # Bottom border
    array[:, 0] = 1        # Left border
    array[:, -1] = 1       # Right border

    return array

# Example usage
rows = 5
cols = 5
border_array = create_border_array(rows, cols)

print(border_array)
